package emu.grasscutter.game.dungeons.enums;

public enum DungunEntryType {
    DUNGEN_ENTRY_TYPE_NONE,
    DUNGEN_ENTRY_TYPE_AVATAR_EXP,
    DUNGEN_ENTRY_TYPE_WEAPON_PROMOTE,
    DUNGEN_ENTRY_TYPE_AVATAR_TALENT,
    DUNGEN_ENTRY_TYPE_RELIQUARY,
    DUNGEN_ENTRY_TYPE_SCOIN,
    DUNGEON_ENTRY_TYPE_OBSCURAE,
    DUNGEON_ENTRY_TYPE_NORMAL,
    DUNGEON_ENTRY_TYPE_TRIAL,
    DUNGEON_ENTRY_TYPE_EFFIGY,
    DUNGEON_ENTRY_TYPE_FLEUR_FAIR,
    DUNGEON_ENTRY_TYPE_CHANNELLER_SLAB_ONE_OFF,
    DUNGEON_ENTRY_TYPE_CHANNELLER_SLAB_LOOP,
    DUNGEON_ENTRY_TYPE_BLITZ_RUSH,
    DUNGEON_ENTRY_TYPE_SUMO,
    DUNGEON_ENTRY_TYPE_ACTIVITY,
    DUNGEON_ENTRY_TYPE_HACHI,
    DUNGEON_ENTRY_TYPE_ROLE_COMBAT
}
